server:
  port: 9101

spring:
  application:
    name: baoxiao-admin
##配置turbine信息
  boot:
    admin:
      turbine:
        location: exaple-turbine
        clusters: default
      notify:
        mail:
          enabled: true
          to: michaelloog@qq.com
          from: 394101728@qq.com
          subject: "#{application.name} (#{application.id}) is #{to.status}"
          text: "#{application.name} (#{application.id})\nstatus changed from #{from.status} to #{to.status}\n\n#{application.healthUrl}"
##配置邮件预警信息
  mail:
    host: smtp.qq.com
#    port: 465
    username: 394101728@qq.com
    password: mtqhuymubqphbgef
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.starttls.required: true
    
      

##配置安全访问用户名和密码    
security:
  basic:
    enabled: true
  user:
    name: baoxiao
    password: bx8888

##配置注册中心地址    
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: ${spring.cloud.client.ipAddress}:${server.port}

